import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../../components/Header/Header";
import Footer from "../../components/Footer/Footer";
import Script from "next/script";
import Input from "../../components/Inp/Input";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Imersao alura Spotify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Input />
        <div className="body_container" >
          <div className="container">
            <Header />
            {children}
          </div>
          <Footer />
        </div>
      </body>
      <Script src="/js.js" />
    </html>
  );
}
